### ISSUE TITLE
Participant more data

### ISSUE THREAD

**Issue by MrFastDie** [Drarig29/brackets-model#6]
participant should be able to hold at least an external_id if you want to reference to other systems and set more data based on it. 
I would also like some additional fields like an image, a website and an identifier which marks the team as internal if you have tuniers and want your team to have a custom border or such.

**Comment by Drarig29** [comment]
Those two releases should have added what you wanted:
- https://github.com/Drarig29/brackets-manager.js/releases/tag/v1.5.0
- https://github.com/Drarig29/brackets-manager.js/releases/tag/v1.5.2
